In [ ]:
''' heavily borrowed from https://github.com/GalvanizeDataScience/lectures/blob/Denver/text-classification/frank-burkholder/naive_bayes_sklearn.ipynb'''


In [66]:
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
import random
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score


In [36]:
categories = [0,1]

In [40]:
# twenty_train = fetch_20newsgroups(subset='train', categories=categories,
#                                       shuffle=True, random_state=42)

path_csv = '../data/csv/giant_valid_csv.csv'
df1 = pd.read_csv(path_csv)
# df = df.dropna()
# print(df.columns)
df = df1.fillna("None")
df.drop(['photos', 'videos', 'distance', 'status_changed_at', 'published_at', 'distance', 'contact', 'organization_animal_id', 'type', 'photos'], axis = 1, inplace= True)

df = pd.get_dummies(df, columns=['status'])
df.drop("status_adoptable", axis = 1, inplace=True)
print(df.shape)
# new = old[['A', 'C', 'D']].copy()

df_content = df[["status_adopted", "description"]].copy()
# print(df_content.head())

X = df_content["description"] #data
X.to_numpy()
print(X)

y = df_content["status_adopted"] #target
y.to_numpy()
# print(y)  0 == negative,  1 == positive                                     

(722, 18)
0      Meet Ruff, Ruff is a smaller breed - probably ...
1      ______ DOB/AGE: 07/10/2019 WEIGHT (GROWN):  55...
2      Okay people, prepare yourself for this face. M...
3      Louie is 15 months old and 42 lbs. He is a Ger...
4      My name is Kenny. I&#039;m a 1 yr old, male bo...
                             ...                        
717    Dina is only about 1 1/2 yrs old.   Adoption f...
718    Meet Virgil! Virgil is a happy happy dog! He i...
719    Meet Omar, Omar will be a small/medium sized d...
720    DORA  Female SHEP MIX BRINDLE 13 2DHPP KC 2/15...
721    Meet Nova!  Now that she is done raising her p...
Name: description, Length: 722, dtype: object


array([1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,

In [41]:
print(X[0])

Meet Ruff, Ruff is a smaller breed - probably around 10 lbs at  6-7  months old and a complete mix...


In [42]:
# eighty_percent_of_data = int(len(X) * .8)
# twenty_percent_of_data = int(len(X) * .2)

# X_train = X[:eighty_percent_of_data]
# y_train = y[:eighty_percent_of_data]
# X_test = X[:twenty_percent_of_data]
# y_test = y[:eighty_percent_of_data]
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [43]:
# print(df_content.head())
# print(X)
# print(y)
print(len(X_train)) #577
print(len(y_train)) #577

577
577


In [58]:
#TODO make my own stopwords list
count_vect = CountVectorizer(lowercase=True, tokenizer=None, stop_words='english',
                             analyzer='word', max_df=1.0, min_df=1,
                             max_features=None)

count_vect.fit(X)

target_names = y

In [59]:
print(count_vect)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


In [60]:

X_counts = count_vect.transform(X)
print("The type of X_counts is {0}.".format(type(X_counts)))
print("The X matrix has {0} rows (documents) and {1} columns (words).".format(
        X_counts.shape[0], X_counts.shape[1]))

The type of X_counts is <class 'scipy.sparse.csr.csr_matrix'>.
The X matrix has 722 rows (documents) and 1753 columns (words).


In [62]:
tfidf_transformer = TfidfTransformer(use_idf=True)
tfidf_transformer.fit(X_counts)
X_tfidf = tfidf_transformer.transform(X_counts)

In [64]:
y.values

array([1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y.values, test_size=0.2, random_state=42)

In [75]:
nb_model = MultinomialNB(alpha=1.0, fit_prior=True, class_prior=None)
nb_model.fit(X_train, y_train);


In [76]:
feature_words = count_vect.get_feature_names()
n = 20 #number of top words associated with the category that we wish to see

for cat in range(len(categories)):
    print(f"\nTarget: {cat}, name: {target_names[cat]}")
    log_prob = nb_model.feature_log_prob_[cat]
    i_topn = np.argsort(log_prob)[::-1][:n]
    features_topn = [feature_words[i] for i in i_topn]
    print(f"Top {n} tokens: ", features_topn)


Target: 0, name: 1
Top 20 tokens:  ['old', 'good', 'adoption', 'mix', 'amp', 'dogs', 'sweet', 'loves', 'year', 'girl', 'dog', 'meet', 'years', 'female', 'pit', 'pounds', 'application', 'website', 'shelter', 'foster']

Target: 1, name: 1
Top 20 tokens:  ['old', 'adoption', 'mix', 'application', 'online', 'website', 'official', 'sweet', 'year', 'meet', 'home', 'looking', 'dog', '039', 'amp', 'forever', 'puppy', 'years', 'dogs', 'loves']


In [77]:
y_predicted = nb_model.predict(X_test)
# X_test[0]

In [78]:
y_predicted

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint8)

In [81]:
from sklearn.metrics import f1_score
f1_score(y_test, y_predicted)


0.8373983739837398

In [86]:
y_pred_proba = nb_model.predict_proba(X_test)[:,1]
y_pred_proba

array([0.73839094, 0.78013778, 0.86613738, 0.91703649, 0.82210813,
       0.89736222, 0.64970209, 0.97857231, 0.61729211, 0.78835884,
       0.69789281, 0.80765324, 0.65986287, 0.63361632, 0.74009866,
       0.60738438, 0.72437236, 0.69844021, 0.73341305, 0.98413922,
       0.84041125, 0.87084287, 0.69844021, 0.97857231, 0.81512269,
       0.51829908, 0.68470418, 0.895138  , 0.72883612, 0.79822952,
       0.63001786, 0.9363682 , 0.92585116, 0.69844021, 0.70106064,
       0.59799212, 0.69844021, 0.62477217, 0.81231049, 0.81429038,
       0.80874568, 0.83710784, 0.85924169, 0.97061661, 0.69844021,
       0.74516362, 0.97857231, 0.8642114 , 0.57937982, 0.76104058,
       0.67102758, 0.71930099, 0.72168104, 0.79515969, 0.93602649,
       0.89538821, 0.29806398, 0.65520687, 0.82469423, 0.83594117,
       0.70994205, 0.66805145, 0.72528225, 0.85373854, 0.77362091,
       0.77157528, 0.77109597, 0.62500715, 0.84540649, 0.63148413,
       0.71969035, 0.89529518, 0.89559158, 0.59126199, 0.67477

In [88]:
thresh=0.7
y_pred = (y_pred_proba>=thresh).astype(int)
y_pred

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1])

In [89]:
f1_score(y_test, y_pred)

0.7783251231527093

In [12]:
# from sklearn.pipeline import Pipeline
# nb_pipeline = Pipeline([('vect', CountVectorizer()),
#                         ('tfidf', TfidfTransformer()),
#                         ('model', MultinomialNB()),
#                         ])
# nb_pipeline.fit(twenty_train.data, twenty_train.target);

In [13]:
twenty_test = fetch_20newsgroups(subset='test', categories=categories,
                                     shuffle=True, random_state=42)
docs_test = twenty_test.data
predicted = nb_pipeline.predict(docs_test)
accuracy = np.mean(predicted == twenty_test.target)
print("\nThe accuracy on the test set is {0:0.3f}.".format(accuracy))


The accuracy on the test set is 0.835.


In [14]:
len(docs_test)


1502